### ISSUE TITLE
Docker icon

### ISSUE THREAD

**Issue by betatim** [kdungs/latex-fontmfizz#1]
The docker icon is missing. Could you point me to some instructions on how to add it? PR will follow.

**Comment by betatim** [comment]
_bump_

**Comment by codextremist** [comment]
+1

**Comment by kdungs** [comment]
Could you do me a favour and review #2 before I merge it to master? I've submitted the underlying release to CTAN but it would be nice to give the structure of this repo a little extra thought. Maybe you prefer to have the `.sty` and the example separated from the generator etc. :)

**Comment by codextremist** [comment]
Hi Kevin,
If you want I can open a pull request and merge my current project which is actually based in your project.
Actually, I did a pure `bash` generator so we could have the `sty` build automatically with no external script dependencies. Also, I included the official font-mfizz repo as a `submodule` so we can always build it whenever they release a new version
Check it out here [https://github.com/codextremist/latex-fontmfizz](https://github.com/codextremist/latex-fontmfizz).
Also I included a Dockerfile with the font-mfizz development environment, so we can generate our own SVG files and send PRs to them

**Comment by kdungs** [comment]
Hi Felipe,

ah the beauty of FOSS 😃  If you're too lazy, someone else will do it, nice! Now I almost feel like I wasted the afternoon yesterday. 😄 

Seems like I had the same idea with including their repo as a submodule. I agree that having Python and especially `jinja2` as a (at this point even implicit) dependency is not ideal.

Now that the CTAN release is done anyway, maybe we can take a step back together and think about how to separate the concerns. As far as I see it there are two use cases:

1.  Someone wants to just use the package but for some reason doesn't get it from CTAN. (Is this even a likely scenario?)
2. Someone wants to build their own version because the CTAN one has once again become outdated.

My original idea was to have a repo that is a 1:1 reflection of what's available in CTAN. Now with the (two) generator(s), there are a bunch of possible ways:

1. Have only the generator in GitHub, basically like your repo, which can build the `.sty` from scratch. Ideally automated and/or without external dependencies. And ideally also with a quick way to generate a CTAN release.
2. Have the CTAN release in the master branch and a dedicated branch for the generator. Discoverability might be a bit low here but it gives a clear separation of concerns.
3. Basically 2. but with two separate repositories.
4. _Something else that I'm missing?_

Let me know what you think. I'd be more than happy to ditch my Python-based solution if it means people will be able to generate the file with less hassle.

Cheers,
Kevin

**Comment by codextremist** [comment]
Hi Kevin,
I'm not familiar with CTAN, actually I have never worked with CTAN before. How they manage new releases and versions? Can we release the packages automatically or do we need to perform any manual steps?
One additional step to the ones you already added is asking the font-mfizz administrator to add a Github Webhook to us, so we know there is something new in their master branch. That would be the trigger for our build script to generate the `sty` with new icons (and possibly push it automatically to CTAN)

**Comment by kdungs** [comment]
AFAIK, [CTAN](https://www.ctan.org/?lang=en) is the central (La)TeX package repository. If I understand it correctly, it's where `tlmgr` gets its packages from. So for example after fontmfizz was released on CTAN the first time around, a few days later by running `sudo tlmgr update -all` you'd get it into your local TeX distribution.

Their release process is anything but automated. There's an [online form](https://www.ctan.org/upload) that one needs to fill out and the uploaded zip will be manually processed by a human. _(If we want to go crazy, it might be possible to send that form automatically but they might not allow cross-site requests to prevent spam…)_

I like the idea of asking for a webhook on font-mfizz. Setting up Travis to automatically produce a release (at least as far as GitHub is concerned) should be easy. Uploading that manually to CTAN is not a lot of work :)

**Comment by betatim** [comment]
:+1: for travis to build things. Not sure about the submodule and the webhook. submodules seem to always cause pain (in the long run) and for the webhook I think if travis builds everything then all that is needed for a new version is that someone submits a PR updating the version number in the docs etc and then travis builds a new release. One thing to investigate is where could travis upload the files it creates? On CircleCI you can store build artefacts that are accessible after the build completes (-> download the zip, upload to CTAN), not sure what travis has.
