### ISSUE TITLE
The font-mfizz.ttf is not the correct one

### ISSUE THREAD

**Issue by AllenLi65536** [kdungs/latex-fontmfizz#4]
The file is not the correct version and I have to download the correct one from https://github.com/fizzed/font-mfizz/releases

**Comment by kdungs** [comment]
Thanks a lot for the feedback! This is very interesting. You're correct. The font itself wasn't updated on the last commit. I've been using this on different machines since then and it never came up. It seems that the release on CTAN actually contains the correct file and it's just the repo that contains the old file.

I fixed this in 4a9f007.
